version: '3'
services:
  web:
    image: php:7.0.33-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MONGO_HOST: mongo
    depends_on:
      - db
      - mongo

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"